url: http://khayyam.org
baseurl: 

# Site settings
title: Khayyam Workshop
email: contact@Khayyam.org
description: "Machine Learning in Astronomy and Physics"


# Team names, titles and social links
people:
- name: Reza Mansouri
  pic: 1
  position: IPM & Sharif University of Technology
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #	
- name: Rahim Moradi
  pic: 2
  position: ICRANet & University of Rome - Sapienza
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Yu Wang
  pic: 3
  position: ICRANet & University of Rome - Sapienza
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- name: Soroush Shakeri
  pic: 4
  position: IPM
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- name: Carlos Brandt
  pic: 0
  position: Affiliation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- name: Name Name
  pic: 0
  position: Affiliation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty